### PR TITLE
Fix issue where bananas are shared between players

### LINKED ISSUE #59: Banana bombs seem to have shared inventory across players
https://forum.entelect.co.za/t/rules-changes-after-early-bird-showdown/756/13

Add unit test to check for this

Early assumptions indicate that the worms banana count might be linked to the agent class

### PR DESCRIPTION
**Pull request by Mistborn94**
Closes #59

### CODE REVIEW

File: game-engine/src/commonMain/kotlin/za/co/entelect/challenge/game/engine/player/Weapon.kt [hunk 1]
```diff
@@ -1,6 +1,6 @@
 package za.co.entelect.challenge.game.engine.player
 
-class Weapon(
+data class Weapon(
```
Comment (Blaarkies) [inline game-engine/src/commonMain/kotlin/za/co/entelect/challenge/game/engine/player/Weapon.kt]: 😮
